### ISSUE TITLE
Bug con macro de LaTeX  \lstset y TeXtidote

### ISSUE THREAD

**Issue by danigonzser** [danigonzser/proyecto-tfg#36]
Un error con TeXtidote puede bloquear la comprobación gramatical y ortográfica en CI. El bug se debe a que la macro de latex \lstset para el diseño de fragmentos de código no se elimina aun poniéndolo en el argumento de `--remove-macros` de TeXtidote.
![image](https://github.com/danigonzser/proyecto-tfg/assets/21023099/3a613a70-2ee9-4b1f-9917-8813697aa435)

Opciones de TeXtidote:
```
--output html
--check es
--dict ./diccionario/diccionario.es.txt
--ignore sh:seclen,sh:stacked,sh:nonp,sh:nobreak,sh:nsubdiv,sh:figref,lt:es:SPANISH_WORD_REPEAT_BEGINNING_RULE
--remove titlepage,titlepage,centering,textwidth,cleardoublepage,centeroffset,oddsidemargin,evensidemargin,large
--remove-macros cleardoublepage,bfseries,today,tableofcontents,listoffigures,listoftables,lstset,textit
```

He visto que la [issue](https://github.com/sylvainhalle/textidote/issues/253) en el repositorio de TeXtidote puede ser el problema.

**Comment by JJ** [comment]
¿Y incluirlo en otro fichero e ignorar lo que haya en ficheros con un patrón determinado?

**Comment by JJ** [comment]
Otra cosa que tendrías que plantearte es para qué usas `lstset`. ¿Hasta qué punto es útil para #2 ?
