### ISSUE TITLE
No existe un análisis del problema

### ISSUE THREAD

**Issue by danigonzser** [danigonzser/proyecto-tfg#39]
Esta issue, que aborda la falta de un análisis del problema, está directamente relacionada con #2 ya que sin un análisis detallado del problema, es difícil garantizar que la memoria del proyecto sea clara y coherente, lo cual es esencial para cumplir con los requisitos de los tutores y el tribunal.

Documentar este análisis no solo mejorará la calidad de la memoria, sino que también asegurará que tanto tutor como tribunal tengan una comprensión común y precisa de los desafíos a abordar, alineando así todas las historias de usuario pertinentes con los objetivos del proyecto.

**Comment by JJ** [comment]
Todos los issues tienen que estar enlazado con una historia de usuario. En este caso se refiere al texto, por lo tanto tiene que tener relación con la HU #2 , pero también por supuesto con las historias de usuario con las que describas el problema.
Es conveniente también que se escriba el texto tratando de cubrir las rúbricas que se usan para evaluación, y que están disponibles en la página web de TFGs en la ETSIIT. Ahí puedes ver claramente qué es lo que van a evaluar de la memoria y cómo y por tanto cómo hay que analizar el problema.
En general, tiene que haber un camino directo (y reversible) entre cualquier línea de código en el repositorio y una historia de usuario y al revés. Este camino es imprescindible para poder evaluar la adecuación del mismo a los requisitos del cliente, que es lo fundamental en desarrollo ágil.
