### ISSUE TITLE
La memoria debe compilar correctamente

### ISSUE THREAD

**Issue by JJ** [danigonzser/proyecto-tfg#7]
Y si aparece algún error de compilación, debemos saberlo inmediatamente (y siempre antes de fusionar el PR correspondiente). Tanto #2 como el tutor necesitan que compile correctamente.

**Comment by danigonzser** [comment]
Esta parte se va a completar haciendo un test comprobando la compilación correcta de la memoria.

**Comment by JJ** [comment]
En general, las soluciones debes  comentarlas en los mensajes de commit en los que añadas el código. Los issues no necesitan ningún tipo de comentario, salvo que quieras exponer diferentes opciones (que no vayan a ir a la memoria)
