### ISSUE TITLE
La memoria no debe tener errores ortográficos ni gramaticales

### ISSUE THREAD

**Issue by JJ** [danigonzser/proyecto-tfg#8]
#2 requiere que la memoria esté escrita correctamente y que transcriba correctamente el trabajo hecho; por otro lado el desarrollo ágil hace énfasis en la calidad, y esta calidad debe reflejarse en la documentación.

**Comment by danigonzser** [comment]
Esta parte se va a completar por la parte de visual studio code con una [extensión](https://marketplace.visualstudio.com/items?itemName=valentjn.vscode-ltex) que chequea la gramática y ortografía además de un workflow con la github action de [textidote-action](https://github.com/ChiefGokhlayeh/textidote-action).

Lo reflejaré en la memoria.
