### ISSUE TITLE
README.md no actualizado con el progreso del proyecto

### ISSUE THREAD

**Issue by danigonzser** [danigonzser/proyecto-tfg#9]
Issue enlazada con #2 para que el README.md se actualice con el progreso del proyecto para todo el que quiera seguir el progreso y sepa como instalar, configurar y desplegar en local la solución en desarrollo.

**Comment by JJ** [comment]
Aunque está bastante mejor, no indicas por qué README.md no está adaptado o qué problemas de adaptación tiene, con lo que sería más fácil diagnosticar el problema y por tanto resolverlo.

**Comment by danigonzser** [comment]
Osea que sería mejor algo como "El archivo README.md no contiene las decisiones tomadas ni el cómo adaptar la infraestructura a otro repositorio"? o "El archivo README.md se debe ir actualizando con las decisiones tomadas además de cómo adaptar la infraestrcutura a otro repositorio." suponiendo que no se está actualizando? @JJ

**Comment by JJ** [comment]
Recuerda que esto no es una historia de usuario, sólo un issue asignado a la #2
